language: node_js
node_js:
- 12
cache:
  yarn: true
  npm: true
install:
- npm install serverless -g
- yarn install
- sls config credentials --stage dev --provider aws --key "${aws_access_key_id}" --secret "${aws_secret_access_key}"
script:
- yarn build
- yarn deploy
env:
  global:
  - secure: TA9QjJyGUPxZlSqrJuNK+Ug72uBwBciVl6hFZm7wc6ve966ieCgqXzIahhrrZqUKLIGddGRmOJQAWB+e2C0I3qyhBLzRbKbn5zSQ11R9goT//RhSQ+M8FLlB4dFhnMVcP7KtyGFAOUdfhgTtHH5fyut75Y4Zq9uuROjwXxhVA4Es1aWlpJGsFvQKqGZenCJn6g21dXkxq0tLcCUbI4VfgjxU1eEFBYFfsX3O7xja3I28x1oxXZS7/M88/XXeoxdtVaPFLNGjuEUPlMizOCfEFkcdofM4wo4GgvjXCfqhBthek6wWeBaZKleojNspjSHdc8lWWSYWcVya+0UK9gYPt6ckRC1zJ7s316S9U3RuZTUNxoJbHJzYXXM4x6BYA+l7od93M/ZWPgGQoe93Ots6AhxzEK9ASIhBh0M+twv30Hh1bsYpllz4qfrmh0VdCNy3lBz9/5WvrlpSFPUPtwNBTxyVNcm7tdlRbwA6tbvtXhF6EVgJRuMyuJh7No2Y9wru5DWizvWMp4wuPX2Dja+xKIhUt0SqsoX/z7XMqIE8HtdyrUWq+3AAx1G0RCJ9v0KERRU+eTl+ot6dNBdGabKx+DokA4dta9VFj8e0kcl8NqWbINQu8iYeZi8AW0eVK3/DdUaUvR5nhOlHDIMnS1vJ8/fcy/ufg7ORmWNfndn4pqg=
  - secure: ClnK2U5+zPiB+1SJQz1mC9WWDH0YI9sVuQjnrN4eWANLNyEskzi4a+aHRVj79cvZK54Yn2MubbPUPb2sLqPJOXBZ6hzuQLQTjkh04rWU9iT+IkpE8l6DTQ4ldqIBFmFom4OL6Fs3awI7CWhMRLgsXDz0LNRCgLg99us4TOspu2Dt5tEhBTYc2WB3J0zdLCN5L0PHAWyuVVAyoYU9LrG1YR65mxK3YjGpVFX3X+x+VLEk+kUeeOYhcmQXQ1gvSYixAPwBgq4DXNswzyRsu8iwkcJPThwZdzruaT/Z4DJoJ4NVsC19ql6Mecu0u3a2qXntiBP+ZHP150nXA5W09cnYgqC2hQaQNG13hhvsDNfavSXjjmynP8aWZKtjZr2UTw98DVMlPjxOKEe1rfVqgo2wI6E+oCm6Tk/osPZsNb0l/iRW+sVH8wADLGXdXkx4l1qehRp/b9UO9ZaRUqMHXYFbyvL5w4gW+Dj9YcgRXa5to2wMStxGBRBE43pbDFbh1Cjc7ptrK8aPjURWaO/F/JNzIhIJr+2CGx6RsmNNucrLpppx/5uiRg51Xm+3nx5MoPj3edg/Km1knd72A0XhFfrdwsh5G3Q/iaO8MiSINPmAz44+a37SLZtjPkcwupRwCWB6Bl99icMFnMYyWiWNT+eLVopRZ8yN6hirjosiI3yeHqc=
